title: Michael Anthonys Pizzeria and Restaurant
description: Our wonderful restaurant in Long Island, NY!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Our Restaurant Page: https://michaelanthonyspizzany.com/

search_enabled: true

search.heading_level: 2
